"""
omxs_engine.py — D1-ACCEL OMX Stockholm strategies for dashboard.
Reads pre-computed omxs_results.json (generated by d1_accel_omxs.py).
Falls back to running the simulation if the file is missing/stale.
"""
import json, logging, time
from pathlib import Path

log = logging.getLogger(__name__)

STALE_HOURS = 24   # regenerate if results older than this


def run_omxs(data_root: Path) -> dict:
    """Return dict of strategy entries for dashboard. Keys: omxs_top3, omxs_top5."""
    results_path = data_root / "omxs_results.json"

    # Check cached results
    if results_path.exists():
        age_h = (time.time() - results_path.stat().st_mtime) / 3600
        if age_h < STALE_HOURS:
            try:
                with open(results_path) as f:
                    data = json.load(f)
                if data:
                    log.info("OMXS: loaded cached results (%d strategies, %.1fh old)",
                             len(data), age_h)
                    return data
            except Exception as e:
                log.warning("OMXS: failed to read cache: %s", e)

    # Run the simulation
    log.info("OMXS: running simulation (cache missing or stale) …")
    try:
        import sys
        sys.path.insert(0, str(data_root))
        from d1_accel_omxs import main as omxs_main
        omxs_main()
        if results_path.exists():
            with open(results_path) as f:
                data = json.load(f)
            log.info("OMXS: simulation complete (%d strategies)", len(data))
            return data
    except Exception as e:
        log.warning("OMXS: simulation failed: %s", e)

    return {}
