"""
omxs_engine.py — D1-ACCEL OMX Stockholm strategies for dashboard.
Prefers omxs_gates_results.json (3-gate comparison); falls back to omxs_results.json.
Both files are generated by the research scripts in the project root.
"""
import json, logging, time
from pathlib import Path

log = logging.getLogger(__name__)

STALE_HOURS = 48


def _load_json(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def run_omxs(data_root: Path) -> dict:
    """
    Return dict of strategy entries for dashboard.

    Priority:
      1. omxs_gates_results.json  — 3-gate comparison (no_gate / spy_gate / omxs_gate)
      2. omxs_results.json        — legacy single-gate results
    """
    gates_path  = data_root / "omxs_gates_results.json"
    legacy_path = data_root / "omxs_results.json"

    # Try gates results first (richer, more informative)
    for path in [gates_path, legacy_path]:
        if not path.exists():
            continue
        age_h = (time.time() - path.stat().st_mtime) / 3600
        if age_h >= STALE_HOURS:
            log.info("OMXS: %s is %.1fh old (stale threshold=%dh), regeneration needed",
                     path.name, age_h, STALE_HOURS)
        try:
            data = _load_json(path)
            if data:
                log.info("OMXS: loaded %s (%d strategies, %.1fh old)",
                         path.name, len(data), age_h)
                return data
        except Exception as e:
            log.warning("OMXS: failed to read %s: %s", path.name, e)

    log.warning("OMXS: no results file found, returning empty")
    return {}
