"""
stoxx600_engine.py — Euro STOXX D1-ACCEL strategies for dashboard.
Reads results/stoxx600_results.json generated by d1_accel_stoxx600.py.
"""
import json, logging, time
from pathlib import Path

log = logging.getLogger(__name__)

STALE_HOURS = 48


def run_stoxx600(data_root: Path) -> tuple[dict, dict]:
    """
    Return (strategies_dict, company_info_dict) for dashboard.
    strategies_dict maps key → strategy entry.
    company_info_dict maps ticker → {name, sector}.
    """
    path = data_root / "results" / "stoxx600_results.json"
    if not path.exists():
        log.warning("STOXX600: stoxx600_results.json not found in %s", data_root)
        return {}, {}

    age_h = (time.time() - path.stat().st_mtime) / 3600
    if age_h >= STALE_HOURS:
        log.info("STOXX600: %s is %.1fh old", path.name, age_h)

    try:
        data = json.loads(path.read_text())
        strategies   = data.get("strategies", {})
        company_info = data.get("company_info", {})
        bench        = data.get("benchmark", {})
        for v in strategies.values():
            v.setdefault("benchmark", bench)
        log.info("STOXX600: loaded %d strategies, %d tickers (%.1fh old)",
                 len(strategies), len(company_info), age_h)
        return strategies, company_info
    except Exception as e:
        log.warning("STOXX600: failed to read %s: %s", path.name, e)
        return {}, {}
